# .github/workflows/plan.yml
name: terraform-security-checks

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "policies-as-code/**"
  workflow_dispatch:

jobs:
  security_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.7

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12

      - name: OPA unit tests
        run: opa test policies-as-code/opa -v
