name: terraform-security-checks

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "policies-as-code/**"
      - ".github/workflows/plan.yml"
  workflow_dispatch:

jobs:
  security_checks:
    runs-on: ubuntu-latest
    env:
      WORK_DIR: envs/dev
      OPA_DIR: policies-as-code/opa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (no backend)
        run: terraform -chdir=${{ env.WORK_DIR }} init -backend=false -input=false

      - name: Terraform Format & Validate
        run: |
          terraform -chdir=${{ env.WORK_DIR }} fmt -check
          terraform -chdir=${{ env.WORK_DIR }} validate

      # tfsec without the action (install binary)
      - name: Install tfsec
        run: |
          curl -sL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
          chmod +x tfsec && sudo mv tfsec /usr/local/bin/tfsec
          tfsec --version
      - name: Run tfsec (soft)
        run: tfsec ${{ env.WORK_DIR }} --no-module-downloads --soft-fail
        continue-on-error: true

      - name: Checkov (soft)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.WORK_DIR }}
        continue-on-error: true

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa && sudo mv opa /usr/local/bin/opa
          opa version

      - name: OPA unit tests (soft)
        run: opa test ${{ env.OPA_DIR }} -v
        continue-on-error: true
